String Transform
========================================================

# Reverser
```{r}
reverser <- function(x) {
    newFunc = strsplit(x, split = "")
    ans = newFunc[[1]][1:nchar(x)]
    return(rev(ans))
}
reverser("fabian")
```

# Scrambler
```{r}
scrambler <- function(x) {
    newFunc = strsplit(x, split = "")
    ans = newFunc[[1]][1:nchar(x)]
    return(sample(ans))
}
scrambler("macalester")
```

# Vowel Bleeper
```{r}
vowelsOut <- function(x) {
    ans = gsub("[aeiou]", "*", x)
    return(ans)
}
vowelsOut("supercalafragalisticexpialadoshus")
```

# L33t

```{r}
L33t <- function(x) {
    newFunc = gsub("e", "3", x)
    newFunc1 = gsub("o", "0", newFunc)
    newFunc2 = gsub("s", "5", newFunc1)
    newFunc3 = gsub("g", "9", newFunc2)

    return(newFunc3)
}
L33t("geography")
```

# Sets of Words 

```{r}
x <- c("good", "sour", "hello")
sapply(x, FUN = L33t)
```

```{r}
L33tApply <- function(x) {
    sapply(x, FUN = L33t)
}
L33t(c("good", "sour"))
```

```{r}
x <- c("fabian", "kaplan")
sapply(x, FUN = vowelsOut)

L33t <- function(input) {
    sapply(input, FUN = vowelsOut)
}

L33t(c("fabian", "kaplan"))
```


