Fabian Arrizon 
========================================================

## Currently

* I am a second-year student at [Macalester College](www.macalester.edu) majoring in Economics and minoring in Statistics. I also play for the [Macalester football](http://athletics.macalester.edu/index.aspx?path=football&tab=football2) team as a defensive player.   

## Previously 

* I was in Northern California for the summer enjoying time with my family and friends. I also worked for a company called [Prime Party Rentals](http://www.primepartyrentals.com/) that decorates weddings and corporate events. It was a great experience for me because I was exposed to many aspects of buisness such as management and planning. 

## Background 

* I was born in Southern California, but I am from a city in Northern California called [Hayward](https://maps.google.com/maps?q=hayward+c&ie=UTF-8&hq=&hnear=0x808f9431b601597d:0x70474dec26939c0,Hayward,+CA&gl=us&ei=e4U4UqmdGOaMyAGqlYG4Cw&ved=0CK8BELYDMAo). I grew up with my parents and an older sister for most of my childhood. It was not until the age of nine that I had a younger brother to look after. 


## Professional Photo 


[Fabian Arrizon](http://athletics.macalester.edu/images/2013/9/2/fabian_arrizon_13_crop.jpg)

## Contact Information

* Phone Number: 510.815.8164


